Forms submitting and displaying
Kachev/Capston-Project pull request #4
Opened 2023-03-30 11:04 UTC by Kachev

2023-03-31 13:42 UTC, PReichetanz requested changes
Nice work! Found some issues to discuss, but a really good implementation for your user story 🚀

2023-03-31 13:42 UTC, PReichetanz commented on components/Button/index.js
> +}
Looks like prettier is not working on saving a file. Please check the VSCode config for the prettier extension.

2023-03-31 13:42 UTC, PReichetanz commented on components/Button/index.js
> +  return <StyledButton type={type} onClick={onClick}>{children}</StyledButton>;
You are not doing anything with the `type` prop, are you?

2023-03-31 13:42 UTC, PReichetanz commented on components/Customer/CustomerCard/index.js
> +const H1 = styled.h1`
I suggest a name which reflects the styled component: `StyledHeadlineOne` or similar.

2023-03-31 13:42 UTC, PReichetanz commented on components/Customer/CustomerForm/index.js
> +const FormContainer = styled.fieldset`
A `fieldset` is part of a form, but not the container of a form. I see what you are going to do, but rename this styled component to `StyledFormFieldset` or similar to be more specific.

2023-03-31 13:42 UTC, PReichetanz commented on components/Customer/CustomerForm/index.test.js
> +  expect(screen.getByText("Adresse")).toBeInTheDocument();
To test for accessibility here as well, use `getByLabelText`.

2023-03-31 13:42 UTC, PReichetanz commented on components/NewForm/index.js
> +          <Button>Fertigstellen</Button>
I think this button needs at least a `type` prop, does it?

2023-03-31 13:42 UTC, PReichetanz commented on components/ReportsLists/index.js
> +const H3 = styled.h3`
As mentioned for `H1` above.

2023-03-31 13:42 UTC, PReichetanz commented on components/ReportsLists/index.js
> +const H2 = styled.h2`
Please don't abbreviate names for styled components, future Hristo can thank me later.

2023-03-31 13:42 UTC, PReichetanz commented on components/ReportsLists/index.js
> +`;
Please use prettier on saving the file.

2023-03-31 13:42 UTC, PReichetanz commented on components/ReportsLists/index.js
> +              <P><b>Adresse: </b>{workReport["customer_address"]}</P>
I would not abbreviate JSX names here.

2023-03-31 13:42 UTC, PReichetanz commented on components/ReportsLists/index.js
> +      <StyledUl>
Because you've set the `list-style-type: none`.
```suggestion
      <StyledUl role="list">
```

2023-03-31 13:42 UTC, PReichetanz commented on components/TimeCard/index.js
> +  text-align: center;
Prettier and abbreviations.

2023-03-31 13:42 UTC, PReichetanz commented on components/TimeForm/index.js
> +  border-radius: 0.5rem;
If these are the same styles as in the `CustomerForm`, you can reuse the styled components from there.

2023-03-31 13:42 UTC, PReichetanz commented on components/TimeForm/index.js
> +  return (
Please use prettier to avoid empty lines.

2023-03-31 13:42 UTC, PReichetanz commented on components/TimeForm/index.test.js
> +  expect(screen.getByText("Pause")).toBeInTheDocument();
I recommend using `getByLabelText` here.

2023-03-31 13:42 UTC, PReichetanz commented on pages/ReportsList/index.js
> +  const [newWorkReports, _] = useLocalStorageState("workReport", {
So you are not using the localStorage to save any information? Why implementing it at all then?

2023-03-31 13:42 UTC, PReichetanz commented on pages/index.js
> +  );
If you need these extra lines for better readability, it's fine; otherwise, use prettier to remove them.

2023-04-03 08:13 UTC, SarahWett approved these changes
Well done! :) 
Good adaption of the given feedback.

2023-04-04 08:12 UTC, merged